### ISSUE TITLE
Passive Gatherings From NetCraft  'set-cookie'

### ISSUE THREAD

**Issue by ethicalhack3r** [RandomStormProjects/Bluto#11]
Run latest version of Bluto and get the below then Bluto exits.

```
Passive Gatherings From NetCraft

'set-cookie'
```

Can reproduce with `azlyrics.com` domain.

**Comment by darryllane** [comment]
Running version 1.1.22? This was resolved i had thought. Give me a mo ill test latest version

**Comment by darryllane** [comment]
Latest version doesnt seem to have the probs hun ^_^. Let me know what version your running. I was using a netcraft lib but ive moved away from it made my own function to gather the data.

**Comment by ethicalhack3r** [comment]
Thanks for checking! Seems an issue on my side then... updated Bluto but still showing version v1.1.20 😕

**Comment by darryllane** [comment]
Hmmm odd, maybe uninstall and reinstall
