### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by deks7er** [RandomStormProjects/Bluto#3]
Brute Forcing Sub-Domains

Note:
While you are waiting we will gather email addresses.
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/bin/bluto", line 319, in googlesearch
    if default_s == True:
UnboundLocalError: local variable 'default_s' referenced before assignment

Hi, there is an issue right after starting the bruteforce.

**Comment by darryllane** [comment]
Hiya, which version are you running? Latest version is 1.1.8, upgrade, if your still having this problem let me know.

**Comment by deks7er** [comment]
v1.1.8

**Comment by darryllane** [comment]
Can you please uninstall and reinstall.

**Comment by deks7er** [comment]
Did, still the same error.

**Comment by darryllane** [comment]
Some logic issues were fixed last night and released to the same version number (by mistake) that's why I asked for you to uninstall and reinstall).

**Comment by darryllane** [comment]
I have just gone through the code again and cant find any issues of this sort. I also noticed you have a traceback response the latest current version is capturing all exceptions. Can you please let me know what OS you have install Bluto on? It could be that its not cleaning up the files after an uninstall maybe.

**Comment by deks7er** [comment]
Ubuntu 14.04 LTS 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

But i just updated as well, the problem persists. 

Btw please add and if statement on dead connections with pass and msg on:
HTTPConnectionPool(host='searchdns.netcraft.com', port=80): Max retries exceeded with url: /?host=*.github.com&last=desktop.github.com&from=81&restriction=site%20contains&position=limited (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f29bca54f10>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by darryllane** [comment]
Ok I worked out what the problem was I have just pushed `1.1.9`. Can you elaborate on what you mean by an `if` statement. Feel free to fork and show me (Ive not seen the above error happen before)

**Comment by darryllane** [comment]
Has this been sorted dude?

**Comment by deks7er** [comment]
sorry for not answering earlier, everything is fine now. 
Thank you.

**Comment by darryllane** [comment]
Great thanks for letting me know. Keep an eye out for future updates. Ive got a lot to add to bluto :)
